name: untitled
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  image: ^4.5.4
  dio: any
  uuid: any
  crypto: any

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
